name: isml
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - diffusers
      - accelerate
      - ema-pytorch
